# Generated by Django 3.1.1 on 2020-09-13 09:33

import datetime
from django.conf import settings
import django.contrib.postgres.fields.citext
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import django_lifecycle.mixins
import exclusivebooleanfield.fields
import trainerdex.fields
import trainerdex.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', django.contrib.postgres.fields.citext.CICharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 3-15 characters. Letters and digits only. Must match Pokemon Go Nickname.', max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]{3,15}$', 'Only letters and numbers are allowed.', 'invalid')], verbose_name='nickname')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('country', django_countries.fields.CountryField(blank=True, help_text='Where this account plays the most. Used to place in localized leaderboards', max_length=2, null=True, verbose_name='country')),
                ('is_banned', models.BooleanField(default=False, help_text='Designates whether this user should be treated as banned. Select this instead of deleting accounts.', verbose_name='banned')),
                ('tid', models.PositiveIntegerField(blank=True, editable=False, help_text="The Trainer ID on the old TrainerDex API. This is deprecated and will be removed upon the retirement of API v1, as it's now shared with the User ID.", null=True, verbose_name='(Deprecated) TID')),
                ('start_date', models.DateField(help_text='Creation date of the Pokémon Go profile.', null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2016, 7, 5))], verbose_name='Start Date')),
                ('is_verified', models.BooleanField(default=False, help_text='Designates whether this user should be treated as verified.', verbose_name='Verified')),
            ],
            options={
                'verbose_name': 'trainer',
                'verbose_name_plural': 'trainers',
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
            managers=[
                ('objects', trainerdex.models.TrainerManager()),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_pk', models.CharField(max_length=36)),
                ('content_field', models.CharField(choices=[('trainer.profile', 'Trainer'), ('update.total_xp', 'Update.Total XP'), ('update.pokedex_total_caught', 'Update.Unique Species Caught'), ('update.pokedex_total_seen', 'Update.Unique Species Seen'), ('update.pokedex_gen1', 'Update.Kanto'), ('update.pokedex_gen2', 'Update.Johto'), ('update.pokedex_gen3', 'Update.Hoenn'), ('update.pokedex_gen4', 'Update.Sinnoh'), ('update.pokedex_gen5', 'Update.Unova'), ('update.pokedex_gen6', 'Update.Kalos'), ('update.pokedex_gen7', 'Update.Alola'), ('update.pokedex_gen8', 'Update.Galar'), ('update.travel_km', 'Update.Jogger (Distance Walked)'), ('update.capture_total', 'Update.Collector (Pokémon Caught)'), ('update.evolved_total', 'Update.Scientist'), ('update.hatched_total', 'Update.Breeder'), ('update.pokestops_visited', 'Update.Backpacker (PokéStops Visited)'), ('update.big_magikarp', 'Update.Fisher'), ('update.battle_attack_won', 'Update.Battle Girl'), ('update.battle_training_won', 'Update.Ace Trainer'), ('update.small_rattata', 'Update.Youngster'), ('update.pikachu', 'Update.Pikachu Fan'), ('update.unown', 'Update.Unown'), ('update.raid_battle_won', 'Update.Champion'), ('update.legendary_battle_won', 'Update.Battle Legend'), ('update.berries_fed', 'Update.Berry Master'), ('update.hours_defended', 'Update.Gym Leader'), ('update.challenge_quests', 'Update.Pokémon Ranger'), ('update.max_level_friends', 'Update.Idol'), ('update.trading', 'Update.Gentleman'), ('update.trading_distance', 'Update.Pilot'), ('update.great_league', 'Update.Great League Veteran'), ('update.ultra_league', 'Update.Ultra League Veteran'), ('update.master_league', 'Update.Master League Veteran'), ('update.photobomb', 'Update.Cameraman'), ('update.pokemon_purified', 'Update.Purifier'), ('update.rocket_grunts_defeated', 'Update.Hero'), ('update.rocket_giovanni_defeated', 'Update.Ulta Hero'), ('update.buddy_best', 'Update.Best Buddy'), ('update.wayfarer', 'Update.Wayfarer'), ('update.total_mega_evos', 'Update.Successor'), ('update.unique_mega_evos', 'Update.Wayfarer'), ('update.type_normal', 'Update.Schoolkid'), ('update.type_fighting', 'Update.Black Belt'), ('update.type_flying', 'Update.Bird Keeper'), ('update.type_poison', 'Update.Punk Girl'), ('update.type_ground', 'Update.Ruin Maniac'), ('update.type_rock', 'Update.Hiker'), ('update.type_bug', 'Update.Bug Catcher'), ('update.type_ghost', 'Update.Hex Maniac'), ('update.type_steel', 'Update.Rail Staff'), ('update.type_fire', 'Update.Kindler'), ('update.type_water', 'Update.Swimmer'), ('update.type_grass', 'Update.Gardener'), ('update.type_electric', 'Update.Rocker'), ('update.type_psychic', 'Update.Psychic'), ('update.type_ice', 'Update.Skier'), ('update.type_dragon', 'Update.Dragon Tamer'), ('update.type_dark', 'Update.Delinquent'), ('update.type_fairy', 'Update.Fairy Tale Girl'), ('update.gymbadges_total', 'Update.Gym Badges'), ('update.gymbadges_gold', 'Update.Gold Gym Badges'), ('update.stardust', 'Update.Stardust')], max_length=31)),
                ('approval', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(('app_label', 'trainerdex'), ('model__in', ['trainer', 'update'])), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='model')),
            ],
            options={
                'verbose_name': 'evidence',
                'verbose_name_plural': 'evidence',
            },
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(0, 'Teamless'), (1, 'Mystic'), (2, 'Valor'), (3, 'Instinct')], primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(3)])),
            ],
            options={
                'verbose_name': 'teams',
            },
        ),
        migrations.CreateModel(
            name='PresetTargetGroup',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'target group',
                'verbose_name_plural': 'target groups',
            },
        ),
        migrations.CreateModel(
            name='FriendCode',
            fields=[
                ('trainer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='friend_code', serialize=False, to='trainerdex.trainer', verbose_name='trainer')),
                ('code', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('(\\d{4}[\\s\\-]?){3}', 'Trainer Code must be 12 digits long and contain only numbers and whitespace.', 'invalid'), django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(15)], verbose_name='Trainer Code')),
            ],
            options={
                'verbose_name': 'Trainer Code',
                'permissions': [('share_friend_code_to_groups', "Trainer Code can be seen by users of groups they're in"), ('share_friend_code_to_web', 'Trainer Code can be seen on the web, publicly'), ('share_friend_code_to_api', 'Trainer Code can be on the API')],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time Updated')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Submitted')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('comment', models.TextField(blank=True, max_length=240, null=True, verbose_name='Comment')),
                ('metadata', models.JSONField(default=dict, help_text='This is a JSON dictionary allowing for as much metadata as you please.\n            However, the following attributes are expected:\n\n            `provider`: string\n            `ocr`: boolean\n            `image_url`: string\n\n            ', verbose_name='Metadata')),
                ('total_xp', trainerdex.fields.PogoPositiveIntegerField(blank=True, null=True, verbose_name='Total XP')),
                ('pokedex_total_caught', trainerdex.fields.PogoPositiveIntegerField(blank=True, null=True, verbose_name='Unique Species Caught')),
                ('pokedex_total_seen', trainerdex.fields.PogoPositiveIntegerField(blank=True, null=True, verbose_name='Unique Species Seen')),
                ('pokedex_gen1', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Register {0} Kanto region Pokémon in the Pokédex.', null=True, validators=[django.core.validators.MaxValueValidator(151)], verbose_name='Kanto')),
                ('pokedex_gen2', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Register {0} Pokémon first discovered in the Johto region to the Pokédex.', null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Johto')),
                ('pokedex_gen3', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Register {0} Pokémon first discovered in the Hoenn region to the Pokédex.', null=True, validators=[django.core.validators.MaxValueValidator(134)], verbose_name='Hoenn')),
                ('pokedex_gen4', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Register {0} Pokémon first discovered in the Sinnoh region to the Pokédex.', null=True, validators=[django.core.validators.MaxValueValidator(107)], verbose_name='Sinnoh')),
                ('pokedex_gen5', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Register {0} Pokémon first discovered in the Unova region to the Pokédex.', null=True, validators=[django.core.validators.MaxValueValidator(156)], verbose_name='Unova')),
                ('pokedex_gen6', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Register {0} Pokémon first discovered in the Kalos region to the Pokédex.', null=True, validators=[django.core.validators.MaxValueValidator(72)], verbose_name='Kalos')),
                ('pokedex_gen7', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Register {0} Pokémon first discovered in the Alola region to the Pokédex.', null=True, validators=[django.core.validators.MaxValueValidator(88)], verbose_name='Alola')),
                ('pokedex_gen8', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Register {0} Pokémon first discovered in the Galar region to the Pokédex.', null=True, validators=[django.core.validators.MaxValueValidator(87)], verbose_name='Galar')),
                ('travel_km', trainerdex.fields.PogoDecimalField(blank=True, decimal_places=2, help_text='Walk {0} km', max_digits=16, null=True, verbose_name='Jogger (Distance Walked)')),
                ('capture_total', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Catch {0} Pokémon.', null=True, verbose_name='Collector (Pokémon Caught)')),
                ('evolved_total', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Evolve {0} Pokémon.', null=True, verbose_name='Scientist')),
                ('hatched_total', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Hatch {0} eggs.', null=True, verbose_name='Breeder')),
                ('pokestops_visited', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Visit {0} PokéStops.', null=True, verbose_name='Backpacker (PokéStops Visited)')),
                ('big_magikarp', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Catch {0} big Magikarp.', null=True, verbose_name='Fisher')),
                ('battle_attack_won', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Win {0} Gym battles.', null=True, verbose_name='Battle Girl')),
                ('battle_training_won', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Train {0} times.', null=True, verbose_name='Ace Trainer')),
                ('small_rattata', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Catch {0} tiny Rattata.', null=True, verbose_name='Youngster')),
                ('pikachu', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Catch {0} Pikachu.', null=True, verbose_name='Pikachu Fan')),
                ('unown', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Catch {0} Unown.', null=True, validators=[django.core.validators.MaxValueValidator(28)], verbose_name='Unown')),
                ('raid_battle_won', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Win {0} Raids.', null=True, verbose_name='Champion')),
                ('legendary_battle_won', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Win {0} Legendary Raids.', null=True, verbose_name='Battle Legend')),
                ('berries_fed', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Feed {0} Berries at Gyms.', null=True, verbose_name='Berry Master')),
                ('hours_defended', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Defend Gyms for {0} hours.', null=True, verbose_name='Gym Leader')),
                ('challenge_quests', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Complete {0} Field Research tasks.', null=True, verbose_name='Pokémon Ranger')),
                ('max_level_friends', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Become Best Friends with {0} Trainers.', null=True, verbose_name='Idol')),
                ('trading', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Trade {0} Pokémon.', null=True, verbose_name='Gentleman')),
                ('trading_distance', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Earn {0} km across the distance of all Pokémon trades.', null=True, verbose_name='Pilot')),
                ('great_league', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Win {} Trainer Battles in the Great League.', null=True, verbose_name='Great League Veteran')),
                ('ultra_league', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Win {} Trainer Battles in the Ultra League.', null=True, verbose_name='Ultra League Veteran')),
                ('master_league', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Win {} Trainer Battles in the Master League.', null=True, verbose_name='Master League Veteran')),
                ('photobomb', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Have {0} surprise encounters in AR Snapshot.', null=True, verbose_name='Cameraman')),
                ('pokemon_purified', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Purify {0} Shadow Pokémon.', null=True, verbose_name='Purifier')),
                ('rocket_grunts_defeated', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Defeat {0} Team GO Rocket Grunts.', null=True, verbose_name='Hero')),
                ('rocket_giovanni_defeated', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Defeat the Team GO Rocket Boss {0} times.', null=True, verbose_name='Ulta Hero')),
                ('buddy_best', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Have {0} Best Buddies.', null=True, verbose_name='Best Buddy')),
                ('wayfarer', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Earn {0} Wayfarer Agreements', null=True, verbose_name='Wayfarer')),
                ('total_mega_evos', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Mega Evolve a Pokémon {0} times.', null=True, verbose_name='Successor')),
                ('unique_mega_evos', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Mega Evolve {0} different species of Pokémon.', null=True, verbose_name='Wayfarer')),
                ('type_normal', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Catch {0} Normal-type Pokémon', null=True, verbose_name='Schoolkid')),
                ('type_fighting', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Catch {0} Fighting-type Pokémon', null=True, verbose_name='Black Belt')),
                ('type_flying', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Catch {0} Flying-type Pokémon', null=True, verbose_name='Bird Keeper')),
                ('type_poison', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Catch {0} Poison-type Pokémon', null=True, verbose_name='Punk Girl')),
                ('type_ground', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Catch {0} Ground-type Pokémon', null=True, verbose_name='Ruin Maniac')),
                ('type_rock', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Catch {0} Rock-type Pokémon', null=True, verbose_name='Hiker')),
                ('type_bug', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Catch {0} Bug-type Pokémon', null=True, verbose_name='Bug Catcher')),
                ('type_ghost', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Catch {0} Ghost-type Pokémon', null=True, verbose_name='Hex Maniac')),
                ('type_steel', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Catch {0} Steel-type Pokémon.', null=True, verbose_name='Rail Staff')),
                ('type_fire', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Catch {0} Fire-type Pokémon', null=True, verbose_name='Kindler')),
                ('type_water', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Catch {0} Water-type Pokémon', null=True, verbose_name='Swimmer')),
                ('type_grass', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Catch {0} Grass-type Pokémon', null=True, verbose_name='Gardener')),
                ('type_electric', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Catch {0} Electric-type Pokémon', null=True, verbose_name='Rocker')),
                ('type_psychic', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Catch {0} Pychic-type Pokémon', null=True, verbose_name='Psychic')),
                ('type_ice', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Catch {0} Ice-type Pokémon', null=True, verbose_name='Skier')),
                ('type_dragon', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Catch {0} Dragon-type Pokémon', null=True, verbose_name='Dragon Tamer')),
                ('type_dark', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Catch {0} Dark-type Pokémon', null=True, verbose_name='Delinquent')),
                ('type_fairy', trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Catch {0} Fairy-type Pokémon', null=True, verbose_name='Fairy Tale Girl')),
                ('gymbadges_total', trainerdex.fields.PogoPositiveIntegerField(blank=True, null=True, verbose_name='Gym Badges')),
                ('gymbadges_gold', trainerdex.fields.PogoPositiveIntegerField(blank=True, null=True, verbose_name='Gold Gym Badges')),
                ('stardust', trainerdex.fields.PogoPositiveIntegerField(blank=True, null=True, verbose_name='Stardust')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to=settings.AUTH_USER_MODEL, verbose_name='trainer')),
            ],
            options={
                'verbose_name': 'update',
                'verbose_name_plural': 'updates',
                'ordering': ['-update_time'],
                'get_latest_by': 'update_time',
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='name')),
                ('stat', models.CharField(choices=[('total_xp', 'Total XP'), ('pokedex_total_caught', 'Unique Species Caught'), ('pokedex_total_seen', 'Unique Species Seen'), ('pokedex_gen1', 'Kanto'), ('pokedex_gen2', 'Johto'), ('pokedex_gen3', 'Hoenn'), ('pokedex_gen4', 'Sinnoh'), ('pokedex_gen5', 'Unova'), ('pokedex_gen6', 'Kalos'), ('pokedex_gen7', 'Alola'), ('pokedex_gen8', 'Galar'), ('travel_km', 'Jogger (Distance Walked)'), ('capture_total', 'Collector (Pokémon Caught)'), ('evolved_total', 'Scientist'), ('hatched_total', 'Breeder'), ('pokestops_visited', 'Backpacker (PokéStops Visited)'), ('big_magikarp', 'Fisher'), ('battle_attack_won', 'Battle Girl'), ('battle_training_won', 'Ace Trainer'), ('small_rattata', 'Youngster'), ('pikachu', 'Pikachu Fan'), ('unown', 'Unown'), ('raid_battle_won', 'Champion'), ('legendary_battle_won', 'Battle Legend'), ('berries_fed', 'Berry Master'), ('hours_defended', 'Gym Leader'), ('challenge_quests', 'Pokémon Ranger'), ('max_level_friends', 'Idol'), ('trading', 'Gentleman'), ('trading_distance', 'Pilot'), ('great_league', 'Great League Veteran'), ('ultra_league', 'Ultra League Veteran'), ('master_league', 'Master League Veteran'), ('photobomb', 'Cameraman'), ('pokemon_purified', 'Purifier'), ('rocket_grunts_defeated', 'Hero'), ('rocket_giovanni_defeated', 'Ulta Hero'), ('buddy_best', 'Best Buddy'), ('wayfarer', 'Wayfarer'), ('total_mega_evos', 'Successor'), ('unique_mega_evos', 'Wayfarer'), ('type_normal', 'Schoolkid'), ('type_fighting', 'Black Belt'), ('type_flying', 'Bird Keeper'), ('type_poison', 'Punk Girl'), ('type_ground', 'Ruin Maniac'), ('type_rock', 'Hiker'), ('type_bug', 'Bug Catcher'), ('type_ghost', 'Hex Maniac'), ('type_steel', 'Rail Staff'), ('type_fire', 'Kindler'), ('type_water', 'Swimmer'), ('type_grass', 'Gardener'), ('type_electric', 'Rocker'), ('type_psychic', 'Psychic'), ('type_ice', 'Skier'), ('type_dragon', 'Dragon Tamer'), ('type_dark', 'Delinquent'), ('type_fairy', 'Fairy Tale Girl')], max_length=24, verbose_name='stat')),
                ('_target', models.CharField(max_length=16, verbose_name='target')),
                ('has_reached', models.BooleanField(default=False, help_text='Designates whether this target has been reached.', verbose_name='reached')),
                ('date_reached', models.DateTimeField(blank=True, help_text='The date the target was reached, if known.', null=True, verbose_name='date reached')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to=settings.AUTH_USER_MODEL, verbose_name='trainer')),
            ],
            options={
                'verbose_name': 'target',
                'verbose_name_plural': 'targets',
                'ordering': ['stat', '_target'],
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PresetTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.CharField(choices=[('total_xp', 'Total XP'), ('pokedex_total_caught', 'Unique Species Caught'), ('pokedex_total_seen', 'Unique Species Seen'), ('pokedex_gen1', 'Kanto'), ('pokedex_gen2', 'Johto'), ('pokedex_gen3', 'Hoenn'), ('pokedex_gen4', 'Sinnoh'), ('pokedex_gen5', 'Unova'), ('pokedex_gen6', 'Kalos'), ('pokedex_gen7', 'Alola'), ('pokedex_gen8', 'Galar'), ('travel_km', 'Jogger (Distance Walked)'), ('capture_total', 'Collector (Pokémon Caught)'), ('evolved_total', 'Scientist'), ('hatched_total', 'Breeder'), ('pokestops_visited', 'Backpacker (PokéStops Visited)'), ('big_magikarp', 'Fisher'), ('battle_attack_won', 'Battle Girl'), ('battle_training_won', 'Ace Trainer'), ('small_rattata', 'Youngster'), ('pikachu', 'Pikachu Fan'), ('unown', 'Unown'), ('raid_battle_won', 'Champion'), ('legendary_battle_won', 'Battle Legend'), ('berries_fed', 'Berry Master'), ('hours_defended', 'Gym Leader'), ('challenge_quests', 'Pokémon Ranger'), ('max_level_friends', 'Idol'), ('trading', 'Gentleman'), ('trading_distance', 'Pilot'), ('great_league', 'Great League Veteran'), ('ultra_league', 'Ultra League Veteran'), ('master_league', 'Master League Veteran'), ('photobomb', 'Cameraman'), ('pokemon_purified', 'Purifier'), ('rocket_grunts_defeated', 'Hero'), ('rocket_giovanni_defeated', 'Ulta Hero'), ('buddy_best', 'Best Buddy'), ('wayfarer', 'Wayfarer'), ('total_mega_evos', 'Successor'), ('unique_mega_evos', 'Wayfarer'), ('type_normal', 'Schoolkid'), ('type_fighting', 'Black Belt'), ('type_flying', 'Bird Keeper'), ('type_poison', 'Punk Girl'), ('type_ground', 'Ruin Maniac'), ('type_rock', 'Hiker'), ('type_bug', 'Bug Catcher'), ('type_ghost', 'Hex Maniac'), ('type_steel', 'Rail Staff'), ('type_fire', 'Kindler'), ('type_water', 'Swimmer'), ('type_grass', 'Gardener'), ('type_electric', 'Rocker'), ('type_psychic', 'Psychic'), ('type_ice', 'Skier'), ('type_dragon', 'Dragon Tamer'), ('type_dark', 'Delinquent'), ('type_fairy', 'Fairy Tale Girl')], max_length=24, verbose_name='stat')),
                ('_target', models.CharField(max_length=16, verbose_name='target')),
                ('name', models.CharField(max_length=200)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='trainerdex.presettargetgroup')),
            ],
            options={
                'verbose_name': 'target (Preset)',
                'verbose_name_plural': 'targets (Preset)',
                'ordering': None,
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EvidenceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='height', upload_to='', width_field='width')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='trainerdex.evidence', verbose_name='evidence')),
            ],
        ),
        migrations.CreateModel(
            name='Codename',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', django.contrib.postgres.fields.citext.CICharField(db_index=True, max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]{3,15}$', 'Only letters and numbers are allowed.', 'invalid')], verbose_name='Nickname')),
                ('active', exclusivebooleanfield.fields.ExclusiveBooleanField(on=('user',))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codenames', to=settings.AUTH_USER_MODEL, verbose_name='trainer')),
            ],
            options={
                'verbose_name': 'Nickname',
                'verbose_name_plural': 'Nicknames',
                'ordering': ['codename'],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='trainer',
            name='faction',
            field=models.ForeignKey(default=0, help_text='The team of the Pokémon Go profile.', on_delete=django.db.models.deletion.PROTECT, to='trainerdex.faction', verbose_name='teams'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddConstraint(
            model_name='target',
            constraint=models.UniqueConstraint(fields=('stat', '_target', 'trainer'), name='unique_target'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='presettarget',
            order_with_respect_to='group',
        ),
        migrations.AddConstraint(
            model_name='evidence',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_pk', 'content_field'), name='unique_request'),
        ),
    ]
