# Generated by Django 3.1.1 on 2020-09-17 10:05

from django.db import migrations, models
import trainerdex.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trainerdex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='content_field',
            field=models.CharField(choices=[('trainer.profile', 'Trainer'), ('update.total_xp', 'Update.Total XP'), ('update.pokedex_total_caught', 'Update.Unique Species Caught'), ('update.pokedex_total_seen', 'Update.Unique Species Seen'), ('update.pokedex_gen1', 'Update.Kanto'), ('update.pokedex_gen2', 'Update.Johto'), ('update.pokedex_gen3', 'Update.Hoenn'), ('update.pokedex_gen4', 'Update.Sinnoh'), ('update.pokedex_gen5', 'Update.Unova'), ('update.pokedex_gen6', 'Update.Kalos'), ('update.pokedex_gen7', 'Update.Alola'), ('update.pokedex_gen8', 'Update.Galar'), ('update.travel_km', 'Update.Jogger (Distance Walked)'), ('update.capture_total', 'Update.Collector (Pokémon Caught)'), ('update.evolved_total', 'Update.Scientist'), ('update.hatched_total', 'Update.Breeder'), ('update.pokestops_visited', 'Update.Backpacker (PokéStops Visited)'), ('update.big_magikarp', 'Update.Fisher'), ('update.battle_attack_won', 'Update.Battle Girl'), ('update.battle_training_won', 'Update.Ace Trainer'), ('update.small_rattata', 'Update.Youngster'), ('update.pikachu', 'Update.Pikachu Fan'), ('update.unown', 'Update.Unown'), ('update.raid_battle_won', 'Update.Champion'), ('update.legendary_battle_won', 'Update.Battle Legend'), ('update.berries_fed', 'Update.Berry Master'), ('update.hours_defended', 'Update.Gym Leader'), ('update.challenge_quests', 'Update.Pokémon Ranger'), ('update.max_level_friends', 'Update.Idol'), ('update.trading', 'Update.Gentleman'), ('update.trading_distance', 'Update.Pilot'), ('update.great_league', 'Update.Great League Veteran'), ('update.ultra_league', 'Update.Ultra League Veteran'), ('update.master_league', 'Update.Master League Veteran'), ('update.photobomb', 'Update.Cameraman'), ('update.pokemon_purified', 'Update.Purifier'), ('update.rocket_grunts_defeated', 'Update.Hero'), ('update.rocket_giovanni_defeated', 'Update.Ulta Hero'), ('update.buddy_best', 'Update.Best Buddy'), ('update.wayfarer', 'Update.Wayfarer'), ('update.total_mega_evos', 'Update.Successor'), ('update.unique_mega_evos', 'Update.Mega Evolution Guru'), ('update.type_normal', 'Update.Schoolkid'), ('update.type_fighting', 'Update.Black Belt'), ('update.type_flying', 'Update.Bird Keeper'), ('update.type_poison', 'Update.Punk Girl'), ('update.type_ground', 'Update.Ruin Maniac'), ('update.type_rock', 'Update.Hiker'), ('update.type_bug', 'Update.Bug Catcher'), ('update.type_ghost', 'Update.Hex Maniac'), ('update.type_steel', 'Update.Rail Staff'), ('update.type_fire', 'Update.Kindler'), ('update.type_water', 'Update.Swimmer'), ('update.type_grass', 'Update.Gardener'), ('update.type_electric', 'Update.Rocker'), ('update.type_psychic', 'Update.Psychic'), ('update.type_ice', 'Update.Skier'), ('update.type_dragon', 'Update.Dragon Tamer'), ('update.type_dark', 'Update.Delinquent'), ('update.type_fairy', 'Update.Fairy Tale Girl'), ('update.gymbadges_total', 'Update.Gym Badges'), ('update.gymbadges_gold', 'Update.Gold Gym Badges'), ('update.stardust', 'Update.Stardust')], max_length=31),
        ),
        migrations.AlterField(
            model_name='presettarget',
            name='stat',
            field=models.CharField(choices=[('total_xp', 'Total XP'), ('pokedex_total_caught', 'Unique Species Caught'), ('pokedex_total_seen', 'Unique Species Seen'), ('pokedex_gen1', 'Kanto'), ('pokedex_gen2', 'Johto'), ('pokedex_gen3', 'Hoenn'), ('pokedex_gen4', 'Sinnoh'), ('pokedex_gen5', 'Unova'), ('pokedex_gen6', 'Kalos'), ('pokedex_gen7', 'Alola'), ('pokedex_gen8', 'Galar'), ('travel_km', 'Jogger (Distance Walked)'), ('capture_total', 'Collector (Pokémon Caught)'), ('evolved_total', 'Scientist'), ('hatched_total', 'Breeder'), ('pokestops_visited', 'Backpacker (PokéStops Visited)'), ('big_magikarp', 'Fisher'), ('battle_attack_won', 'Battle Girl'), ('battle_training_won', 'Ace Trainer'), ('small_rattata', 'Youngster'), ('pikachu', 'Pikachu Fan'), ('unown', 'Unown'), ('raid_battle_won', 'Champion'), ('legendary_battle_won', 'Battle Legend'), ('berries_fed', 'Berry Master'), ('hours_defended', 'Gym Leader'), ('challenge_quests', 'Pokémon Ranger'), ('max_level_friends', 'Idol'), ('trading', 'Gentleman'), ('trading_distance', 'Pilot'), ('great_league', 'Great League Veteran'), ('ultra_league', 'Ultra League Veteran'), ('master_league', 'Master League Veteran'), ('photobomb', 'Cameraman'), ('pokemon_purified', 'Purifier'), ('rocket_grunts_defeated', 'Hero'), ('rocket_giovanni_defeated', 'Ulta Hero'), ('buddy_best', 'Best Buddy'), ('wayfarer', 'Wayfarer'), ('total_mega_evos', 'Successor'), ('unique_mega_evos', 'Mega Evolution Guru'), ('type_normal', 'Schoolkid'), ('type_fighting', 'Black Belt'), ('type_flying', 'Bird Keeper'), ('type_poison', 'Punk Girl'), ('type_ground', 'Ruin Maniac'), ('type_rock', 'Hiker'), ('type_bug', 'Bug Catcher'), ('type_ghost', 'Hex Maniac'), ('type_steel', 'Rail Staff'), ('type_fire', 'Kindler'), ('type_water', 'Swimmer'), ('type_grass', 'Gardener'), ('type_electric', 'Rocker'), ('type_psychic', 'Psychic'), ('type_ice', 'Skier'), ('type_dragon', 'Dragon Tamer'), ('type_dark', 'Delinquent'), ('type_fairy', 'Fairy Tale Girl')], max_length=24, verbose_name='stat'),
        ),
        migrations.AlterField(
            model_name='target',
            name='stat',
            field=models.CharField(choices=[('total_xp', 'Total XP'), ('pokedex_total_caught', 'Unique Species Caught'), ('pokedex_total_seen', 'Unique Species Seen'), ('pokedex_gen1', 'Kanto'), ('pokedex_gen2', 'Johto'), ('pokedex_gen3', 'Hoenn'), ('pokedex_gen4', 'Sinnoh'), ('pokedex_gen5', 'Unova'), ('pokedex_gen6', 'Kalos'), ('pokedex_gen7', 'Alola'), ('pokedex_gen8', 'Galar'), ('travel_km', 'Jogger (Distance Walked)'), ('capture_total', 'Collector (Pokémon Caught)'), ('evolved_total', 'Scientist'), ('hatched_total', 'Breeder'), ('pokestops_visited', 'Backpacker (PokéStops Visited)'), ('big_magikarp', 'Fisher'), ('battle_attack_won', 'Battle Girl'), ('battle_training_won', 'Ace Trainer'), ('small_rattata', 'Youngster'), ('pikachu', 'Pikachu Fan'), ('unown', 'Unown'), ('raid_battle_won', 'Champion'), ('legendary_battle_won', 'Battle Legend'), ('berries_fed', 'Berry Master'), ('hours_defended', 'Gym Leader'), ('challenge_quests', 'Pokémon Ranger'), ('max_level_friends', 'Idol'), ('trading', 'Gentleman'), ('trading_distance', 'Pilot'), ('great_league', 'Great League Veteran'), ('ultra_league', 'Ultra League Veteran'), ('master_league', 'Master League Veteran'), ('photobomb', 'Cameraman'), ('pokemon_purified', 'Purifier'), ('rocket_grunts_defeated', 'Hero'), ('rocket_giovanni_defeated', 'Ulta Hero'), ('buddy_best', 'Best Buddy'), ('wayfarer', 'Wayfarer'), ('total_mega_evos', 'Successor'), ('unique_mega_evos', 'Mega Evolution Guru'), ('type_normal', 'Schoolkid'), ('type_fighting', 'Black Belt'), ('type_flying', 'Bird Keeper'), ('type_poison', 'Punk Girl'), ('type_ground', 'Ruin Maniac'), ('type_rock', 'Hiker'), ('type_bug', 'Bug Catcher'), ('type_ghost', 'Hex Maniac'), ('type_steel', 'Rail Staff'), ('type_fire', 'Kindler'), ('type_water', 'Swimmer'), ('type_grass', 'Gardener'), ('type_electric', 'Rocker'), ('type_psychic', 'Psychic'), ('type_ice', 'Skier'), ('type_dragon', 'Dragon Tamer'), ('type_dark', 'Delinquent'), ('type_fairy', 'Fairy Tale Girl')], max_length=24, verbose_name='stat'),
        ),
        migrations.AlterField(
            model_name='update',
            name='great_league',
            field=trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Win {0} Trainer Battles in the Great League.', null=True, verbose_name='Great League Veteran'),
        ),
        migrations.AlterField(
            model_name='update',
            name='master_league',
            field=trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Win {0} Trainer Battles in the Master League.', null=True, verbose_name='Master League Veteran'),
        ),
        migrations.AlterField(
            model_name='update',
            name='photobomb',
            field=trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Have {0} surprise encounters in GO Snapshot.', null=True, verbose_name='Cameraman'),
        ),
        migrations.AlterField(
            model_name='update',
            name='rocket_giovanni_defeated',
            field=trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Defeat the Team GO Rocket Boss {0} times. ', null=True, verbose_name='Ulta Hero'),
        ),
        migrations.AlterField(
            model_name='update',
            name='travel_km',
            field=trainerdex.fields.PogoDecimalField(blank=True, decimal_places=2, help_text='Walk {0:0,g} km.', max_digits=16, null=True, verbose_name='Jogger (Distance Walked)'),
        ),
        migrations.AlterField(
            model_name='update',
            name='ultra_league',
            field=trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Win {0} Trainer Battles in the Ultra League.', null=True, verbose_name='Ultra League Veteran'),
        ),
        migrations.AlterField(
            model_name='update',
            name='unique_mega_evos',
            field=trainerdex.fields.PogoPositiveIntegerField(blank=True, help_text='Mega Evolve {0} different species of Pokémon.', null=True, verbose_name='Mega Evolution Guru'),
        ),
    ]
