# Generated by Django 3.0.8 on 2020-07-17 12:40

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trainerdex', '0001_rebuild'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='date_reached',
            field=models.DateTimeField(blank=True, help_text='The date the target was reached, if known.', null=True, verbose_name='date reached'),
        ),
        migrations.AddField(
            model_name='target',
            name='has_reached',
            field=models.BooleanField(default=False, help_text='Designates whether this target has been reached.', verbose_name='reached'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='country',
            field=django_countries.fields.CountryField(blank=True, help_text='Where this account plays the most. Used to place in localized leaderboards', max_length=2, null=True, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='is_banned',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as banned. Select this instead of deleting accounts.', verbose_name='banned'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='last modified'),
        ),
    ]
