# Generated by Django 3.0.8 on 2020-07-17 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainerdex', '0002_auto_20200717_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to=settings.AUTH_USER_MODEL, verbose_name='trainer'),
        ),
    ]
