# Generated by Django 3.0.8 on 2020-07-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainerdex', '0003_auto_20200717_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified'),
        ),
    ]
