# Generated by Django 3.0.8 on 2020-07-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainerdex', '0004_update_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='total_xp',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total XP'),
        ),
    ]
