# Generated by Django 3.0.8 on 2020-07-18 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('trainerdex', '0006_auto_20200718_1507'), ('trainerdex', '0007_auto_20200718_1508')]

    dependencies = [
        ('trainerdex', '0005_auto_20200718_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presettarget',
            options={'ordering': None, 'verbose_name': 'target (Preset)', 'verbose_name_plural': 'targets (Preset)'},
        ),
        migrations.RemoveField(
            model_name='presettargetgroup',
            name='children',
        ),
        migrations.AddField(
            model_name='presettarget',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='trainerdex.PresetTargetGroup'),
        ),
        migrations.AddConstraint(
            model_name='target',
            constraint=models.UniqueConstraint(fields=('stat', '_target', 'trainer'), name='unique_target'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='presettarget',
            order_with_respect_to='group',
        ),
        migrations.AlterField(
            model_name='presettarget',
            name='group',
            field=models.ForeignKey(default='total_xp', on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='trainerdex.PresetTargetGroup'),
            preserve_default=False,
        ),
    ]
