# Generated by Django 3.0.8 on 2020-07-08 11:05

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import trainerdex.models


class Migration(migrations.Migration):

    dependencies = [
        ('trainerdex', '0006_auto_20200701_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='id',
            new_name='old_id',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='user',
            new_name='user_ptr',
        ),
        migrations.AlterField(
            model_name='trainer',
            name='start_date',
            field=models.DateField(help_text='The date you created your Pokémon Go account.', null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2016, 7, 5))], verbose_name='Start Date'),
        ),
    ]
