# Generated by Django 3.0.8 on 2020-07-08 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import trainerdex.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainerdex', '0007_auto_20200708_1105'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='trainer',
            managers=[
                ('objects', trainerdex.models.TrainerManager()),
            ],
        ),
        migrations.AlterField(
            model_name='trainer',
            name='user_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='trainer', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
