# Generated by Django 3.0.8 on 2020-07-08 12:08

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trainerdex', '0008_auto_20200708_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='banned',
            new_name='is_banned',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='verified',
            new_name='is_verified',
        ),
        migrations.AlterField(
            model_name='trainer',
            name='is_banned',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as banned. Select this instead of deleting accounts.', verbose_name='Banned'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as verified.', verbose_name='Verified'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='country',
            field=django_countries.fields.CountryField(blank=True, help_text='Where this account plays the most. Used to place in localized leaderboards', max_length=2, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='faction',
            field=models.ForeignKey(default=0, help_text='The team of the Pokémon Go profile.', on_delete=django.db.models.deletion.PROTECT, to='trainerdex.Faction', verbose_name='teams'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='old_id',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='The Trainer ID on the old TrainerDex API. This is deprecated and will be removed upon the retirement of API v1', null=True, verbose_name='(Deprecated) ID'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='start_date',
            field=models.DateField(help_text='The date of creating of the Pokémon Go profile.', null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2016, 7, 5))], verbose_name='Start Date'),
        ),
    ]
