# Generated by Django 3.0.8 on 2020-07-08 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainerdex', '0009_auto_20200708_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faction',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Teamless'), (1, 'Mystic'), (2, 'Valor'), (3, 'Instinct')], primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
    ]
