# Generated by Django 3.0.8 on 2020-07-08 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainerdex', '0010_auto_20200708_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='trainerdex.Trainer', verbose_name='trainer'),
        ),
    ]
