# Generated by Django 3.0.8 on 2020-07-19 00:20

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20200718_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='UTC', verbose_name='timezone'),
        ),
    ]
