# Generated by Django 3.1.1 on 2020-09-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_community_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='language',
            field=models.CharField(choices=[('de', 'German'), ('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('it', 'Italian'), ('ja', 'Japanese'), ('ko', 'Korean'), ('pt-br', 'Brazilian Portuguese'), ('th', 'Thai'), ('zh-hant', 'Traditional Chinese')], default='en-us', max_length=7, verbose_name='language'),
        ),
    ]
