# Generated by Django 3.0.8 on 2020-07-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20200719_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('en-GB', 'English (United Kingdom)'), ('de', 'German'), ('es', 'Spanish'), ('fr', 'French'), ('it', 'Italian'), ('ja', 'Japanese'), ('ko', 'Korean'), ('pt-BR', 'Brazilian Portuguese'), ('zh-TW', 'Traditional Chinese')], default='en', max_length=5, verbose_name='language'),
        ),
    ]
